## 3-3 행렬(Matrix)

행렬은 차수가 1인 벡터를 같은 축 방향으로 나열하는 개념이다. 즉, 여러개의 1차원 벡터를 원소로 갖는 1차원 배열이댜. 원소의 차수가 1이므로 총 차수는 2가 된다. 텐서플로에서는 '랭크-2'라고 부른다.
그림의 왼쪽 그림과 같이 '랭크-2'텐서는 여러개의 1차원 배열('랭크-1' 텐서)을 원소로 갖는 벡터의 형대로 표현된다. 오른쪽 그림과 같이 행(raw)과 열(column)이라는 2개의 축을 갖는 2차원 구조로 표현할 수도 있다. 원소가 되는 1차원 벡터들이 행을 구성하는 단위가 되면, 각 벡터의 동일한 위치에 있는 원소들끼리 열을 구성하는 단위가 된다.

<img src="행렬.jpg" alt="행렬이미지" width="300" style="height: auto;" />

다음 예제는 [[10,20],[30,40]]과 같이, 2개의 리스트를 원소로 갖는 리시트를 사용해서 (2행,2열)구조로 2차원 행렬 텐서를 만드는 내용이다. 앞 부분에서 스칼라와 벡터를 만든것과 같이 constant함수에 배열을 입력하면 텐서로 변환해준다. 2차원 배열을 입력값으로 전달했기 때문에, 함수가 반환하는 텐서는 2차원이 된다.

In [1]:
#라이브러리 불러오기
import tensorflow as tf

list_of_list = [[10,20],[30,40]]

#텐서변환 - constant 함수에 2차원 배열 입력
mat1 = tf.constant(list_of_list)

#랭크 확인
print("rank: ",tf.rank(mat1))

#텐서 출력
print("mat1:",mat1)

rank:  tf.Tensor(2, shape=(), dtype=int32)
mat1: tf.Tensor(
[[10 20]
 [30 40]], shape=(2, 2), dtype=int32)


rank함수로 변환된 행렬 텐서의 차수를 확인해보면 랭크가 2임을 알 수 있다. 행 방향과 열 방향으로 2개의 축이 존재하므로 축의 개수를 나타내는 차수는 2가 된다. 또한, 행렬의 shapedms (2,2)가 되는데 (행의 개수, 열의개수)형태를 나타낸다.
행의 개수는 2차원 배열을 구성하는 벡터의 개수가 되고, 열의 개수는 각 벡터를 구성하는 원소의 개수가 된다.
stack 함수를 사용해서 행렬을 만들 수 있다. 1차원 벡터2개를 stack함수를 이용하여 결합하는 방식이다. 따라서 차수가 2인 랭크-2 텐서가 된다

In [3]:
#1차원 벡터 정의
vec1 = tf.constant([1,0])
vec2 = tf.constant([-1,2])

#텐서 변환 - stack 함수로 1차원 배열을 위아래로 쌓기
mat2 = tf.stack([vec1,vec2])
#랭크 확인
print("rank:",tf.rank(mat2))

#텐서 출력하기
print("mat2:",mat2)

rank: tf.Tensor(2, shape=(), dtype=int32)
mat2: tf.Tensor(
[[ 1  0]
 [-1  2]], shape=(2, 2), dtype=int32)


2차원 구조인 행렬에도 벡터에 적용된 바와 같이 math모듈의 수학 함수들을 그대로 적용할 수 있다. 마찬가지로, 같은 위치에 있는 원소들끼리(element-by-element)짝을 이루어 계산한다.
그림과 다음 예제는 multiply함수를 사용하여 각 원소들을 서로 곱하는 과정을 보여준다.

<img src="행렬연산.jpg" alt="행렬연산" width="300" style="height: auto;" />             

In [5]:
#element-by-element 연산
element_mul = tf.math.multiply(mat1,mat2)
print("result:",element_mul)
print("rank:",tf.rank(element_mul))

result: tf.Tensor(
[[ 10   0]
 [-30  80]], shape=(2, 2), dtype=int32)
rank: tf.Tensor(2, shape=(), dtype=int32)


2차원 행렬에 스칼라 값인 3을 곱하면, 행렬의 모든 원소에 3을 곱하게 된다. 행렬의 원소가 모두 3으로 구성되는 2차원 행렬 형태로 확장되어 연산을 처리하게 된다.

In [6]:
#브로드캐스트 연산
element_bc = tf.math.multiply(mat1,3)
print("result:",element_bc)
print("rank:",tf.rank(element_bc))

result: tf.Tensor(
[[ 30  60]
 [ 90 120]], shape=(2, 2), dtype=int32)
rank: tf.Tensor(2, shape=(), dtype=int32)


선형대수에서 다루는 행렬곱 연산은 matmul함수를 사용하여 처리한다. 행렬곱은 벡터의 선형결합 또는 선형사상등 선형대수학의 기초가 되는 연산이다.

<img src="행렬곱.jpeg" alt="행렬곱" width="300" style="height: auto;" />  

In [8]:
#행렬곱 연산
mat_mul = tf.matmul(mat1,mat2)
print("result:",mat_mul)
print("rank:",tf.rank(mat_mul))

result: tf.Tensor(
[[-10  40]
 [-10  80]], shape=(2, 2), dtype=int32)
rank: tf.Tensor(2, shape=(), dtype=int32)


덧셈 연산은 add함수로 처리한다. 같은 위치에 있는 원소들끼리 더한 값들을 원래 크기와 같은 행렬에 반환된다.

In [9]:
#덧셈연산
add1 = tf.math.add(mat1,mat2)
print("result:",add1)
print("rank:",tf.rank(add1))

result: tf.Tensor(
[[11 20]
 [29 42]], shape=(2, 2), dtype=int32)
rank: tf.Tensor(2, shape=(), dtype=int32)


파이썬 덧셈연산자를 사용해도 같은 결과를 얻을 수 있다.

In [10]:
#덧셈 연산자
add2 = mat1 + mat2
print("result:",add2)
print("rank:",tf.rank(add2))

result: tf.Tensor(
[[11 20]
 [29 42]], shape=(2, 2), dtype=int32)
rank: tf.Tensor(2, shape=(), dtype=int32)


In [ ]:
넘파이 배열을 텐서로 변환할 수 있듯이, 텐서를 넘파이 배열로 변환할 수 있다. numpy() ㅁ